on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "hello world!"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"
      - name: gobuild
        run: make example
